import argparse
from pathlib import Path

from .generation import codegen
from .interpreter import Interpreter
from .ir import IRGenerator
from .lexer import tokenize
from .liveness import Liveness
from .lowering import lower_ir
from .parser import Parser
from .processing import postprocess

DEFAULT_SOURCE_FILE = "examples/language/sample.txt"


def print_ast(node, indent=0):
    prefix = "  " * indent
    if isinstance(node, list):
        for item in node:
            print_ast(item, indent)
    elif hasattr(node, "__dict__"):
        print(f"{prefix}{node.__class__.__name__}:")
        for key, value in node.__dict__.items():
            if isinstance(value, (list, object)) and not isinstance(value, (str, int)):
                print(f"{prefix}  {key}:")
                print_ast(value, indent + 2)
            else:
                print(f"{prefix}  {key}: {value}")
    else:
        print(f"{prefix}{node}")


def interpret(program_node):
    interpreter = Interpreter()
    return interpreter.interpret(program_node)


def generate(program_node):
    generator = IRGenerator()
    generator.generate(program_node)
    generator.close()
    return generator.lines


def analyze_liveness(ir):
    analyzer = Liveness(ir)
    return analyzer.analyze()


def scan_file(file_path: str | Path, show_tokens: bool = False, show_ast: bool = False) -> bool:
    path = Path(file_path)
    if not path.exists():
        print(f"Error: File '{file_path}' not found.")
        return False

    with path.open("r", encoding="utf-8") as file:
        tokens = tokenize(file)

    if show_tokens:
        print("--- Tokens ---")
        for token in tokens:
            print(token)
        print()

    parser = Parser(tokens)
    ast = parser.parse_program()

    if show_ast:
        print("--- AST ---")
        print_ast(ast)
        print()

    interpret(ast)
    ir = generate(ast)
    ir = lower_ir(ir)
    ir, coloring = analyze_liveness(ir)
    opcodes = codegen(ir, coloring)
    for line in postprocess(opcodes):
        print(line)
    return True


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="A simple compiler CLI suite.")
    parser.add_argument(
        "file",
        nargs="?",
        default=DEFAULT_SOURCE_FILE,
        help="The source file to compile and run.",
    )
    parser.add_argument(
        "--tokens",
        action="store_true",
        help="Print the tokens generated by the lexer.",
    )
    parser.add_argument(
        "--ast",
        action="store_true",
        help="Print the Abstract Syntax Tree (AST) generated by the parser.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return 0 if scan_file(args.file, show_tokens=args.tokens, show_ast=args.ast) else 1


if __name__ == "__main__":
    raise SystemExit(main())
