import sys
import argparse
from pathlib import Path

try:
    from .interpreter import Interpreter
    from .ir import IRGenerator
    from .lexer import tokenize
    from .parser import Parser
    from .liveness import Liveness
    from .generation import codegen
except ImportError:
    from .liveness import Liveness
    from interpreter import Interpreter
    from ir import IRGenerator
    from lexer import tokenize
    from parser import Parser
    from generation import codegen

def print_ast(node, indent=0):
    """Recursively prints the AST with indentation."""
    prefix = "  " * indent
    if isinstance(node, list):
        for item in node:
            print_ast(item, indent)
    elif hasattr(node, "__dict__"):
        print(f"{prefix}{node.__class__.__name__}:")
        for key, value in node.__dict__.items():
            if isinstance(value, (list, object)) and not isinstance(value, (str, int)):
                print(f"{prefix}  {key}:")
                print_ast(value, indent + 2)
            else:
                print(f"{prefix}  {key}: {value}")
    else:
        print(f"{prefix}{node}")

def interpret(program_node):
    interpreter = Interpreter()
    return interpreter.interpret(program_node)

def generate(program_node):
    generator = IRGenerator()
    generator.generate(program_node)
    generator.close()
    return generator.lines

def liveness(ir):
    analyzer = Liveness(ir)
    return analyzer.analyze()
    
def scan_file(file_path: str | Path, show_tokens: bool = False, show_ast: bool = False) -> None:
    path = Path(file_path)
    if not path.exists():
        print(f"Error: File '{file_path}' not found.")
        return

    with path.open("r", encoding="utf-8") as file:
        tokens = tokenize(file)
    
    if show_tokens:
        print("--- Tokens ---")
        for token in tokens:
            print(token)
        print()

    parser = Parser(tokens)
    ast = parser.parse_program()

    if show_ast:
        print("--- AST ---")
        print_ast(ast)
        print()

    interpret(ast)
    ir = generate(ast)
    ir, coloring = liveness(ir)
    codegen(ir, coloring)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="A simple compiler CLI suite.")
    parser.add_argument("file", nargs="?", default="sample.txt", help="The source file to compile and run.")
    parser.add_argument("--tokens", action="store_true", help="Print the tokens generated by the lexer.")
    parser.add_argument("--ast", action="store_true", help="Print the Abstract Syntax Tree (AST) generated by the parser.")
    
    args = parser.parse_args()
    scan_file(args.file, show_tokens=args.tokens, show_ast=args.ast)
